In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
birds = pd.read_csv('datasets\\penguins.csv')

In [4]:
birds

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [5]:
birds.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,342.000000,342.000000,342.000000,342.000000,344.000000
mean,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,5.459584,1.974793,14.061714,801.954536,0.818356
min,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,59.600000,21.500000,231.000000,6300.000000,2009.000000

In [6]:
birds.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [7]:
birds['bill_length_mm'] = birds['bill_length_mm'].fillna(birds['bill_length_mm'].mean())
birds['bill_depth_mm'] = birds['bill_depth_mm'].fillna(birds['bill_depth_mm'].mean())
birds['flipper_length_mm'] = birds['flipper_length_mm'].fillna(birds['flipper_length_mm'].mean())
birds['body_mass_g'] = birds['body_mass_g'].fillna(birds['body_mass_g'].mean())
birds['sex'] = birds['sex'].fillna(birds['sex'].mode()[0])

In [8]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), object(3)
memory usage: 21.6+ KB

In [9]:
birds['species'] = birds['species'].astype('category')
birds['island'] = birds['island'].astype('category')
birds['sex'] = birds['sex'].astype('category')
birds['year'] = birds['year'].astype('category')

In [10]:
birds['weight_kilo'] = np.round(birds['body_mass_g'] / 1000, 2)

In [11]:
birds

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight_kilo
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.75
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.80
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.25
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.20
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.45
...,...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.00
340,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.40
341,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.78
342,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.10
343,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.78

In [12]:
birds[(birds['species'] == "Gentoo") & (birds['bill_depth_mm'] == birds['bill_depth_mm'].mean())]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight_kilo
271,Gentoo,Biscoe,43.92193,17.15117,200.915205,4201.754386,male,2009,4.2

In [13]:
max_avg_blength = birds.groupby('species')['bill_length_mm'].mean().idxmax()
max_avg_bdepth = birds.groupby('species')['bill_depth_mm'].mean().idxmax()
max_avg_flength = birds.groupby('species')['flipper_length_mm'].mean().idxmax()
max_avg_bodyg = birds.groupby('species')['body_mass_g'].mean().idxmax()

print(max_avg_blength, max_avg_bdepth, max_avg_flength, max_avg_bodyg)

Chinstrap Chinstrap Gentoo Gentoo

C:\Users\ACER\AppData\Local\Temp\ipykernel_13220\897571521.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  max_avg_blength = birds.groupby('species')['bill_length_mm'].mean().idxmax()
C:\Users\ACER\AppData\Local\Temp\ipykernel_13220\897571521.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  max_avg_bdepth = birds.groupby('species')['bill_depth_mm'].mean().idxmax()
C:\Users\ACER\AppData\Local\Temp\ipykernel_13220\897571521.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  max_avg_flength = birds.groupby('species')['flipper_length_mm'].mean().idxmax()
C:\Users\ACER\AppData\Local\Temp\ipykernel_13220\897571521.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  max_avg_bodyg = birds.groupby('species')['body_mass_g'].mean().idxmax()

In [16]:
birds.groupby(["island", "species"]).mode().idxmax()

C:\Users\ACER\AppData\Local\Temp\ipykernel_13220\2574301662.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  birds.groupby(["island", "species"]).mode().idxmax()

AttributeError: 'DataFrameGroupBy' object has no attribute 'mode'